version: '3'
services:
  postgres:
    image: 'postgres:13.3-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:6.2.4-alpine'

  nginx:
    restart: always
    ports:
      - 3333:80
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    links:
      - client
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./server:/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

    depends_on:
      - postgres
      - redis

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
